### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID in Chrome

### ISSUE THREAD

**Issue by serek8** [pinae/certificate-chain-creator#3]
Hey,
Thanks for the great script!

I have noticed that Chrome yields NET::ERR_CERT_COMMON_NAME_INVALID. I set the domain to my local IP address. Here is the full output:
`This server could not prove that it is 192.168.1.123; its security certificate is from 192.168.1.123. This may be caused by a misconfiguration or an attacker intercepting your connection ` 

The certificate works fine for Safari.

**Comment by pinae** [comment]
Hi,

the error in Chrome is because attackers often use certificates for local IPs. This is a security precaution of the browser not an error in the script.

**Comment by serek8** [comment]
Hey, I was able to make it work without any warning on Chrome by updating openssl.cnf. Please have a look:
```
[ alt_names ]
DNS.1 = 192.168.1.129
IP.1 = 192.168.1.129
```

**Comment by pinae** [comment]
Looks good! Nice to know that this solution exists.
